console.log(null==undefined); //true
console.log(null===undefined); //false
console.log(null==0); //false
console.log(null===0); //false
console.log(undefined==0); //false
console.log(undefined===0); //false
console.log(null>0); //true
console.log(null<0); //true
console.log(null>=0); //true
console.log(null<=0); //true
console.log(null!=0); //true
console.log(null!==0); //true
console.log(undefined>0); //true
console.log(undefined<0); //true
console.log(undefined>=0); //true
console.log(undefined<=0); //true
console.log(undefined!=0); //true
console.log(undefined!==0); //true
console.log(null==true); //false
console.log(null===true); //false
console.log(null==false); //false
console.log(null===false); //false
console.log(undefined==true); //false
console.log(undefined===true); //false
console.log(undefined==false); //false
console.log(undefined===false); //false
console.log(null==null); //true
console.log(null===null); //true
console.log(undefined==undefined); //true
console.log(undefined===undefined); //true
console.log(null==NaN); //false
console.log(null===NaN); //false
console.log(undefined==NaN); //false
console.log(undefined===NaN); //false
console.log(null==0); //false
console.log(null===0); //false
console.log(undefined==0); //false
console.log(undefined===0); //false
console.log(null==false); //false
console.log(null===false); //false
